### ISSUE TITLE
Wait for ipfs id | jq .Addresses not to be empty

### ISSUE THREAD

**Issue by galargh** [ipfs/start-ipfs-daemon-action#5]
https://github.com/ipfs/go-ipfs/pull/8609#discussion_r769702761

**Comment by galargh** [comment]
Make this additional check either opt-in or opt-out. It might make sense for some to start daemon in `offline` mode for example and then the addresses would never be non-empty.

**Comment by lidel** [comment]
This should be enabled by default (opt-out) :+1:

**Comment by galargh** [comment]
Resolved by https://github.com/ipfs/start-ipfs-daemon-action/pull/7
