### ISSUE TITLE
Log full output of ipfs daemon

### ISSUE THREAD

**Issue by lidel** [ipfs/start-ipfs-daemon-action#6]
This is low priority, but we are losing some visibility into why peer may fail to start:

```
( ipfs daemon --enable-gc=false & ) | grep -q 'Daemon is ready'
```

Only stderr will show, and that may not always be the whole picture :) 

Perhaps we could `(ipfs daemon  | tee daemon.log) &` and then in a new line do the grep?

**Comment by galargh** [comment]
Resolved by https://github.com/ipfs/start-ipfs-daemon-action/pull/8
